// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace DoctorVanGogh.OmniCoreDrill {
	[GeneratedCode("Defs.Generated.tt","0.1")]
	[SuppressMessage("ReSharper", "InconsistentNaming")]
	[SuppressMessage("ReSharper", "UnusedMember.Global")]
	[SuppressMessage("ReSharper", "ConvertToAutoProperty")]
	[SuppressMessage("ReSharper", "FieldCanBeMadeReadOnly.Local")]
	[SuppressMessage("ReSharper", "ConvertPropertyToExpressionBody")]
	public partial class DefNames {
		public const string @Thing_CoreDrill = @"CoreDrill";
		public const string @Thing_UnfinishedDrillingPlan = @"UnfinishedDrillingPlan";
	}
}
